### Criar um Centro de Custo
POST http://localhost:3000/centro-custo
Content-Type: application/json

{
    "nome": "Milho",
    "descricao": "Plantação de Milho",
    "agricultorId": "145837fc-ecec-497e-9ef5-7d8c5c4639cc"
}